### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [P4rk/known_side_effects#11]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.1.1. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary known-side-effects -w /tmp/ext known-side-effects==0.1.1
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting known-side-effects==0.1.1
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/c06/038be7efc3414/known_side_effects-0.1.1.tar.gz (5.8 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-z4wum6er/known-side-effects/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-z4wum6er/known-side-effects/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-z4wum6er/known-side-effects/pip-egg-info
         cwd: /tmp/pip-wheel-z4wum6er/known-side-effects/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-z4wum6er/known-side-effects/setup.py", line 3, in <module>
        with open("../README.md", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: '../README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by jayvdb** [comment]
ping @P4rk
